# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Tae Eun Kim
title: Student
email: taeeun.kim@kaist.ac.kr
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  goodtaeeun
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: https://user-images.githubusercontent.com/57384091/128380057-819fce5e-b534-4648-ae7a-b4fd04d546c0.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Tae Eun. I'm currently pursuing my Master's degree in computer science. Learning new things and sharing them is my greatest pleasure! I think research is taking a step further, which is to make/discover new knowledge for the sake of everyone who will benefit from it.

  I am interested in : <mark>Software Engineering</mark> and <mark>Automatic Program Repair</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: ConFixPlus - Automatic Program Repair tool
        link: http://203.252.112.24/
        link_text: Project web demo page
        # additional_links:
        #   - title:  sproogen/modern-resume-theme
        #     icon: fab fa-github
        #     url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Ever wished someone else to fix your bug? This is the moment when dreams come true.
        description: | # this will include new lines to allow paragraphs
          I worked on this project in my undergraduate years. This is an automatic program repair tool, enhanced with a patch recommendation technique to produce patches to fix bugs automatically. The link above will lead you to a page where you can try to fix the bugs from the dataset I used for the validation of the tool. Moreover, you can try to fix a bug from your own repository if you give the necessary information. If you are interested, go check out the website!

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Intelligent Software Engineering Lab
        link: isel.lifove.com
        # link_text: boringcompany.com
        sub_title: Undergrad. Research Intern
        caption: November 2019 - June 2021
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Handong University
        caption: 2014 - 2021
        sub_title: BSc Computer Science
        quote: >
          Established in 1995, Handong is a very good university.
        description: | # this will include new lines to allow paragraphs
          During my time at Harndong I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time in club activities, which were [acapella club](https://www.youtube.com/channel/UCG3D08O95Wc9cvRap5FKhSg) and judo club.
      - layout: left
        title: KAIST
        caption: 2021 fall - now
        sub_title: Master's Student
        quote: >
          KAIST - Korea Advanced Institute of Science and Technology
        description: | # this will include new lines to allow paragraphs
          I am a member of [ProsysLab](https://prosys.kaist.ac.kr/). I have just started my study, my research, my life here at KAIST. I look forward to the wonderful opportunities and people I will encounter during my time here.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - [Singing](https://youtu.be/TwUuTr97Pvw)
      - Judo
      - Watching Movies

#      Look at this cool image  
#      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
